version: '3'

services:
  todotests:
    image: todotests
    environment: 
      - FRONT_HOST = todofrontend
      - FRONT_PORT = 3000
    depends_on:
      - todoback
      - todofront

  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST = todobackend
      - REACT_APP_API_PORT = 3001
    depends_on:
      - todoback

  todoback:
    image: todobackend
    ports:
      - 3001:3001