version: '3'

services:
  todotests:
    image: todotests
    container_name: todotests
    environment: 
      - FRONT_HOST=todofront
    restart: always
    depends_on:
      - todoback
      - todofront

  todofront:
    image: todofrontend
    container_name: todofront
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - todonet
    environment:
      - REACT_APP_API_HOST=localhost
    restart: always
    depends_on:
      - todoback

  todoback:
    image: todobackend
    container_name: todoback
    restart: always
    ports:
      - 127.0.0.1:3001:3001
    networks:
      - todonet
networks:
  todonet:
    driver: bridge